services:
  wa-chat-service:
    image: wa-chat-service:latest
    container_name: wa-chat-service
    ports:
      - "8121:8121"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app_log:/app.log
  meili-search:
    image: getmeili/meilisearch:latest
    container_name: meili-search
    ports:
      - "7700:7700"
    restart: unless-stopped
volumes:
  app_log:
    driver: local
