services:
  wa-chat-service:
    image: wa-chat-service:latest
    container_name: wa-chat-service
    ports:
      - "8121:8121"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - meili-search
  meili-search:
    image: getmeili/meilisearch:v1.42.1
    container_name: meili-search
    ports:
      - "7700:7700"
    restart: unless-stopped
