// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents the structure of a message in the system.
type MessageModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Wamid           string                 `protobuf:"bytes,2,opt,name=wamid,proto3" json:"wamid,omitempty"`
	ChatId          string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageType     string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	MessageCategory string                 `protobuf:"bytes,5,opt,name=message_category,json=messageCategory,proto3" json:"message_category,omitempty"`
	SenderName      string                 `protobuf:"bytes,6,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Payload         string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	StorageMediaId  *string                `protobuf:"bytes,8,opt,name=storage_media_id,json=storageMediaId,proto3,oneof" json:"storage_media_id,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=sent_at,json=sentAt,proto3,oneof" json:"sent_at,omitempty"`
	DeliveredAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=delivered_at,json=deliveredAt,proto3,oneof" json:"delivered_at,omitempty"`
	ReadAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=read_at,json=readAt,proto3,oneof" json:"read_at,omitempty"`
	Error           *string                `protobuf:"bytes,14,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageModel) Reset() {
	*x = MessageModel{}
	mi := &file_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageModel) ProtoMessage() {}

func (x *MessageModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageModel.ProtoReflect.Descriptor instead.
func (*MessageModel) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageModel) GetWamid() string {
	if x != nil {
		return x.Wamid
	}
	return ""
}

func (x *MessageModel) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MessageModel) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MessageModel) GetMessageCategory() string {
	if x != nil {
		return x.MessageCategory
	}
	return ""
}

func (x *MessageModel) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *MessageModel) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *MessageModel) GetStorageMediaId() string {
	if x != nil && x.StorageMediaId != nil {
		return *x.StorageMediaId
	}
	return ""
}

func (x *MessageModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MessageModel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MessageModel) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *MessageModel) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *MessageModel) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *MessageModel) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// SaveMessageRequest contains the message details to be saved and the associated phone number ID.
type SaveMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageModel          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMessageRequest) Reset() {
	*x = SaveMessageRequest{}
	mi := &file_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMessageRequest) ProtoMessage() {}

func (x *SaveMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMessageRequest.ProtoReflect.Descriptor instead.
func (*SaveMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *SaveMessageRequest) GetMessage() *MessageModel {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_v1_message_proto protoreflect.FileDescriptor

const file_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x10v1/message.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf3\x04\n" +
	"\fMessageModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05wamid\x18\x02 \x01(\tR\x05wamid\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12)\n" +
	"\x10message_category\x18\x05 \x01(\tR\x0fmessageCategory\x12\x1f\n" +
	"\vsender_name\x18\x06 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\x12-\n" +
	"\x10storage_media_id\x18\b \x01(\tH\x00R\x0estorageMediaId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\asent_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06sentAt\x88\x01\x01\x12B\n" +
	"\fdelivered_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vdeliveredAt\x88\x01\x01\x128\n" +
	"\aread_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x06readAt\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x0e \x01(\tH\x04R\x05error\x88\x01\x01B\x13\n" +
	"\x11_storage_media_idB\n" +
	"\n" +
	"\b_sent_atB\x0f\n" +
	"\r_delivered_atB\n" +
	"\n" +
	"\b_read_atB\b\n" +
	"\x06_error\"@\n" +
	"\x12SaveMessageRequest\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.v1.MessageModelR\amessage2H\n" +
	"\aMessage\x12=\n" +
	"\vSaveMessage\x12\x16.v1.SaveMessageRequest\x1a\x16.google.protobuf.EmptyB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_v1_message_proto_rawDescOnce sync.Once
	file_v1_message_proto_rawDescData []byte
)

func file_v1_message_proto_rawDescGZIP() []byte {
	file_v1_message_proto_rawDescOnce.Do(func() {
		file_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_message_proto_rawDesc), len(file_v1_message_proto_rawDesc)))
	})
	return file_v1_message_proto_rawDescData
}

var file_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_message_proto_goTypes = []any{
	(*MessageModel)(nil),          // 0: v1.MessageModel
	(*SaveMessageRequest)(nil),    // 1: v1.SaveMessageRequest
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_v1_message_proto_depIdxs = []int32{
	2, // 0: v1.MessageModel.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: v1.MessageModel.sent_at:type_name -> google.protobuf.Timestamp
	2, // 2: v1.MessageModel.delivered_at:type_name -> google.protobuf.Timestamp
	2, // 3: v1.MessageModel.read_at:type_name -> google.protobuf.Timestamp
	0, // 4: v1.SaveMessageRequest.message:type_name -> v1.MessageModel
	1, // 5: v1.Message.SaveMessage:input_type -> v1.SaveMessageRequest
	3, // 6: v1.Message.SaveMessage:output_type -> google.protobuf.Empty
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_message_proto_init() }
func file_v1_message_proto_init() {
	if File_v1_message_proto != nil {
		return
	}
	file_v1_message_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_message_proto_rawDesc), len(file_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_message_proto_goTypes,
		DependencyIndexes: file_v1_message_proto_depIdxs,
		MessageInfos:      file_v1_message_proto_msgTypes,
	}.Build()
	File_v1_message_proto = out.File
	file_v1_message_proto_goTypes = nil
	file_v1_message_proto_depIdxs = nil
}
