// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: v1/storage-media.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SaveMediaIDRequest contains the media ID to be saved and the associated phone number ID.
type SaveMediaIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	PhoneNumberId string                 `protobuf:"bytes,2,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	GrpcCreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=grpc_created_at,json=grpcCreatedAt,proto3" json:"grpc_created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMediaIDRequest) Reset() {
	*x = SaveMediaIDRequest{}
	mi := &file_v1_storage_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMediaIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMediaIDRequest) ProtoMessage() {}

func (x *SaveMediaIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_storage_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMediaIDRequest.ProtoReflect.Descriptor instead.
func (*SaveMediaIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_storage_media_proto_rawDescGZIP(), []int{0}
}

func (x *SaveMediaIDRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *SaveMediaIDRequest) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

func (x *SaveMediaIDRequest) GetGrpcCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GrpcCreatedAt
	}
	return nil
}

// SaveMediaIDResponse indicates whether the media ID was saved successfully.
type SaveMediaIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMediaIDResponse) Reset() {
	*x = SaveMediaIDResponse{}
	mi := &file_v1_storage_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMediaIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMediaIDResponse) ProtoMessage() {}

func (x *SaveMediaIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_storage_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMediaIDResponse.ProtoReflect.Descriptor instead.
func (*SaveMediaIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_storage_media_proto_rawDescGZIP(), []int{1}
}

func (x *SaveMediaIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_v1_storage_media_proto protoreflect.FileDescriptor

const file_v1_storage_media_proto_rawDesc = "" +
	"\n" +
	"\x16v1/storage-media.proto\x12\agrpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\x12SaveMediaIDRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12&\n" +
	"\x0fphone_number_id\x18\x02 \x01(\tR\rphoneNumberId\x12B\n" +
	"\x0fgrpc_created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rgrpcCreatedAt\"%\n" +
	"\x13SaveMediaIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2X\n" +
	"\fStorageMedia\x12H\n" +
	"\vSaveMediaID\x12\x1b.grpc.v1.SaveMediaIDRequest\x1a\x1c.grpc.v1.SaveMediaIDResponseB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_v1_storage_media_proto_rawDescOnce sync.Once
	file_v1_storage_media_proto_rawDescData []byte
)

func file_v1_storage_media_proto_rawDescGZIP() []byte {
	file_v1_storage_media_proto_rawDescOnce.Do(func() {
		file_v1_storage_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_storage_media_proto_rawDesc), len(file_v1_storage_media_proto_rawDesc)))
	})
	return file_v1_storage_media_proto_rawDescData
}

var file_v1_storage_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_storage_media_proto_goTypes = []any{
	(*SaveMediaIDRequest)(nil),    // 0: grpc.v1.SaveMediaIDRequest
	(*SaveMediaIDResponse)(nil),   // 1: grpc.v1.SaveMediaIDResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_v1_storage_media_proto_depIdxs = []int32{
	2, // 0: grpc.v1.SaveMediaIDRequest.grpc_created_at:type_name -> google.protobuf.Timestamp
	0, // 1: grpc.v1.StorageMedia.SaveMediaID:input_type -> grpc.v1.SaveMediaIDRequest
	1, // 2: grpc.v1.StorageMedia.SaveMediaID:output_type -> grpc.v1.SaveMediaIDResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_storage_media_proto_init() }
func file_v1_storage_media_proto_init() {
	if File_v1_storage_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_storage_media_proto_rawDesc), len(file_v1_storage_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_storage_media_proto_goTypes,
		DependencyIndexes: file_v1_storage_media_proto_depIdxs,
		MessageInfos:      file_v1_storage_media_proto_msgTypes,
	}.Build()
	File_v1_storage_media_proto = out.File
	file_v1_storage_media_proto_goTypes = nil
	file_v1_storage_media_proto_depIdxs = nil
}
