// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: v1/storage-media.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageMedia_SaveMediaID_FullMethodName = "/grpc.v1.StorageMedia/SaveMediaID"
)

// StorageMediaClient is the client API for StorageMedia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageMedia defines the gRPC service for managing media.
type StorageMediaClient interface {
	// SaveMediaID saves a media ID and returns the result.
	SaveMediaID(ctx context.Context, in *SaveMediaIDRequest, opts ...grpc.CallOption) (*SaveMediaIDResponse, error)
}

type storageMediaClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageMediaClient(cc grpc.ClientConnInterface) StorageMediaClient {
	return &storageMediaClient{cc}
}

func (c *storageMediaClient) SaveMediaID(ctx context.Context, in *SaveMediaIDRequest, opts ...grpc.CallOption) (*SaveMediaIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMediaIDResponse)
	err := c.cc.Invoke(ctx, StorageMedia_SaveMediaID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageMediaServer is the server API for StorageMedia service.
// All implementations must embed UnimplementedStorageMediaServer
// for forward compatibility.
//
// StorageMedia defines the gRPC service for managing media.
type StorageMediaServer interface {
	// SaveMediaID saves a media ID and returns the result.
	SaveMediaID(context.Context, *SaveMediaIDRequest) (*SaveMediaIDResponse, error)
	mustEmbedUnimplementedStorageMediaServer()
}

// UnimplementedStorageMediaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageMediaServer struct{}

func (UnimplementedStorageMediaServer) SaveMediaID(context.Context, *SaveMediaIDRequest) (*SaveMediaIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveMediaID not implemented")
}
func (UnimplementedStorageMediaServer) mustEmbedUnimplementedStorageMediaServer() {}
func (UnimplementedStorageMediaServer) testEmbeddedByValue()                      {}

// UnsafeStorageMediaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageMediaServer will
// result in compilation errors.
type UnsafeStorageMediaServer interface {
	mustEmbedUnimplementedStorageMediaServer()
}

func RegisterStorageMediaServer(s grpc.ServiceRegistrar, srv StorageMediaServer) {
	// If the following call panics, it indicates UnimplementedStorageMediaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageMedia_ServiceDesc, srv)
}

func _StorageMedia_SaveMediaID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMediaIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageMediaServer).SaveMediaID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageMedia_SaveMediaID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageMediaServer).SaveMediaID(ctx, req.(*SaveMediaIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageMedia_ServiceDesc is the grpc.ServiceDesc for StorageMedia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageMedia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.v1.StorageMedia",
	HandlerType: (*StorageMediaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveMediaID",
			Handler:    _StorageMedia_SaveMediaID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/storage-media.proto",
}
